### ISSUE TITLE
Update release for this project

### ISSUE THREAD

**Issue by irfanhabib** [salsify/avro-schema-registry#259]
The latest release `v.0.12.0` was created in February 2018. We pinned against that release and were exposed to a security vulnerability that has been fixed in `master`. 

It would be awesome if releases could be cut more frequently. We have currently pinned against the HEAD in `master`.

**Comment by jturkel** [comment]
@irfanhabib - We always run the HEAD of `master` in production so that should be generally be stable but we'd be happy to cut releases more often if that's helpful. This project is a little interesting since it's an application rather than a library so when we initially created it we weren't sure how people would want to customize it for things like logging, metrics, and error reporting. How are you handling those kinds of customizations for this project?

**Comment by irfanhabib** [comment]
@jturkel thanks for your response! We would be happy to continue to pin against `master`, if that is stable. However, to avoid confusion for other users of this perhaps you could cut a new release?

> we weren't sure how people would want to customize it for things like logging, metrics, and error reporting.
We've not applied patches for improved logging, error reporting or metrics to the deployments in our environment. We collect metrics from clients of the registry. We use Sentry (sentry.io) for error reporting for all our components.
