### ISSUE TITLE
[question] can I use it for XSD or JSON schemas as well?

### ISSUE THREAD

**Issue by archenroot** [salsify/avro-schema-registry#49]

**Comment by archenroot** [comment]
Thing is that we also have external parties submitting data in multiple formats icluding json and xml files, coul I use this registry to store these "external" schemas at same place as avro?

**Comment by tjwp** [comment]
In the current form, this registry cannot be used to store XSD or JSON schemas instead of Avro. The reason is that the registry does not treat the Avro schemas as opaque strings. The Avro schemas are parsed and identified using a fingerprint that is defined by the Avro project. So the implementation of the registry is pretty Avro specific.

**Comment by jturkel** [comment]
Thanks for submitting this issue but we plan on keeping this project focused on storing Avro schemas.
